---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Designing Open Democracy"
keywords:    "Democracy, edemocracy, voting, opensource, liquid democracy, delegative democracy, sortition"
description: "This is a group for any tech professionals or political experts (or ordinary citizens) interested in discussing in a detailed way the potential opportunities for reforming existing democratic institutions; from local organisations to national governments around the world through technology or other practices. Our aim is to improve democracy: we think this can best be done by providing a forum for discussing democracy proposals, ideas, and to foster collaboration between people who would like to participate in democracy reform.

"
source_link: "http://designingopendemocracy.com/"
favicon:     "http://designingopendemocracy.com/img/dodlogo.ico"
touch_icon:  "http://designingopendemocracy.com/img/dodlogo.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  plainwhite: '#ffffff'
  white:      '#f8f8f8'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'

kramdown:
  auto_ids:  false

